# Generated by Django 4.0.3 on 2022-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('caracteristicas', models.TextField(max_length=500, verbose_name='Características')),
                ('tipo_habitacion', models.CharField(max_length=100, verbose_name='Tipo de Habitación')),
                ('numero_habitacion', models.IntegerField(verbose_name='Número de Habitación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('numero_piso', models.IntegerField(verbose_name='Número de Piso')),
                ('estado_habitacion', models.BooleanField(default=False, verbose_name='Estado Habitación')),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
