# Generated by Django 4.0.3 on 2022-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion_habitacion',
            field=models.TextField(default='Escribir descripción', max_length=500, verbose_name='Descripción de habitación'),
        ),
    ]
