# Generated by Django 4.0.3 on 2022-04-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
    ]
