# Generated by Django 4.0.3 on 2022-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleados_apellidos_alter_empleados_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='dui',
            field=models.IntegerField(unique=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='isss',
            field=models.IntegerField(unique=True, verbose_name='Numero de Afiliado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nup',
            field=models.IntegerField(unique=True, verbose_name='Numero de Pensionado'),
        ),
    ]
