# Generated by Django 4.0.3 on 2022-04-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleados_dui_alter_empleados_isss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.departamento', verbose_name='Departamento'),
        ),
    ]
