# Generated by Django 4.0.3 on 2022-04-17 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleados_id_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.departamento', verbose_name='Departamento'),
        ),
    ]
