# Generated by Django 4.0.3 on 2022-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleados_id_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='email',
            field=models.EmailField(default='email', max_length=254, verbose_name='Email'),
        ),
    ]
